### PR TITLE
Add ArcCheck support

### PR DESCRIPTION
**Pull request by mchamberland**
This adds ArcCheck support. For my purposes, I've added many more fields to write to the csv, such as gamma histogram statistics and CAX offset values. Feedback welcome!

Also, I had trouble with the relative imports, so I adjusted to something that worked on my system. Feel free to suggest to add them back.

### CODE REVIEW

**Comment by cutright** [comment]
Awesome, thanks Marc! I'll test this with my colleague at another institution that has ArcCheck.

As far as the imports, I'm actually not sure what the right way to go about that is.  I prefer imports relative to the app directory, but when I package the application with setup.py for PyPI the imports fail as they need imports relative to the script.  Do you know of a way to handle this?

**Comment by mchamberland** [comment]
Note that it's been tested with the most recent version of SNC Patient / ArcCheck. The reports have changed slightly from past versions.

No, I have no idea how to deal with those imports. The intricacies of Python imports are a mystery to me! I usually just try everything until it works. Feel free to change them back before merging if that's the only way it works with PyPI.

**Comment by mchamberland** [comment]
Okay, I tested with simply calling IQDM from the command line, and you're right, that requires those relative imports. I was calling the script differently when debugging. I'll go back to the relative imports for this pull request.

**Comment by mchamberland** [comment]
Pushed the changes.

I'll be looking for another solution since I won't be calling IQDM from the command line in my use case. If I find anything, I'll open another pull request.

**Pull request merged**
